server:
  servlet-path: /
logging:  
  level:
    com.example.demo: debug
spring:
  thymeleaf:
    cache: false
    prefix: classpath:/static/
    suffix: .html
  # 数据源设置
  datasource:
    username: root
    password: '!RenYao123'
    url: jdbc:mysql://134.175.110.184:3306/seat_order?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    host: 134.175.110.184
    port: 6379
    password: 123456
# mybatis设置
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml

